// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW1QvxPw7_ciSL06Qdk5mOjdAeBI7QeWc',
    appId: '1:104780306420:web:6b1328b0f159117f0f8ba1',
    messagingSenderId: '104780306420',
    projectId: 'sbsr-g',
    authDomain: 'sbsr-g.firebaseapp.com',
    storageBucket: 'sbsr-g.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmfEl9I9R4VwV1rDH0cfBigLFf3MYfQIs',
    appId: '1:104780306420:android:8d3468ee1517f70f0f8ba1',
    messagingSenderId: '104780306420',
    projectId: 'sbsr-g',
    storageBucket: 'sbsr-g.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_gqgApqKp81_aSUhKCZdwsaZZLIqrkY0',
    appId: '1:104780306420:ios:5fd520414dd65dc40f8ba1',
    messagingSenderId: '104780306420',
    projectId: 'sbsr-g',
    storageBucket: 'sbsr-g.appspot.com',
    iosClientId: '104780306420-24aiibofov8i5fh7f3qv5t2qkia3fjtp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sbsrGrad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_gqgApqKp81_aSUhKCZdwsaZZLIqrkY0',
    appId: '1:104780306420:ios:2771b7ecdbdd70a30f8ba1',
    messagingSenderId: '104780306420',
    projectId: 'sbsr-g',
    storageBucket: 'sbsr-g.appspot.com',
    iosClientId: '104780306420-qfmh9btqcbn0mbmbvcq5vtnj3ggol7b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sbsrGrad.RunnerTests',
  );
}
